### ISSUE TITLE
Would you mind updating the code 

### ISSUE THREAD

**Issue by TreemanCHou** [chrisdavis90/ged-syntax-probing#1]
Hi , I am interested in your works after reading your article in CoNLL ([https://aclanthology.org/2022.conll-1.25]) . The article mentioned that your code was released , but it seems nothings is here XD . Could you please share the code ?

**Comment by chrisdavis90** [comment]
Hey, sorry for the delay! I just pushed the code, data, and results

**Comment by TreemanCHou** [comment]
Thank you ! ;-)
